############################
## Navbar
############################

main:
- name: Home
  url: /
  weight: 10
- name: News
  url: /news/
  weight: 20
- name: Publications
  url: /papers/
  weight: 30
- name: Team
  url: /members/
  weight: 40
- name: Join us
  url: /joining/
  weight: 50
- name: About
  url: /about/
  weight: 60
- name: Citing
  url: /cite
  weight: 70
- name: Status
  url: https://vdaraka.ijclab.in2p3.fr/public-dashboards/4f6faf056ad8452e9de2586275ba1f5a
  weight: 80
